### ISSUE TITLE
How can I extract the average style from a set of images instead of a single image?

### ISSUE THREAD

**Issue by hadaev8** [EugenHotaj/pytorch-generative#1]

**Comment by EugenHotaj** [comment]
You could try to use a set of images as the `style_image`, instead of a single image as I'm currently doing. While I haven't tried this, I'm a little skeptical that it will produce good results, unless all the style images are very similar.

An approach that might work better is to use GANs, with the goal to generate an image that the `discriminator` can't tell apart from the other style images. There's a bunch of papers that do exactly this which you can find on arxiv.

**Comment by EugenHotaj** [comment]
There's now support for multiple style images.
