### ISSUE TITLE
How to view progress during training?

### ISSUE THREAD

**Issue by AlexanderGroeger** [EugenHotaj/pytorch-generative#28]
I've ran a PixelCNN in Colab last week, but I didn't know when it would finish (4 hours) because there was no in-training output. If you're concerned about flooding a cell with outputs, you could use tqdm over all the epochs that way the user can still see progress while printing only a few lines.

**Comment by EugenHotaj** [comment]
@AlexanderGroeger the Trainer writes out TensorBoard logs to the `logdir` directory, e.g:
<img width="725" alt="Screen Shot 2021-05-18 at 9 39 06 AM" src="https://user-images.githubusercontent.com/6221162/118661461-22792a00-b7bd-11eb-9878-b1584429278a.png">

You can spin up a TensorBoard server if you're running locally with the command `tensorboard --logdir <logdir>`, or if you're running on Colab with the magic `%tensorboard --logdir <logdir>`.  Does that work for you?

We used to have `tqdm` but it wasn't that helpful because the output becomes overwhelming when you have a lot of metrics and it's easier to interpret metrics in a chart vs. raw dumps. Maybe having a simple bar like you suggest would be useful though. I'm happy to accept pull a pull request if you want to add this.

**Comment by AlexanderGroeger** [comment]
I'm still new to tensorboard, so I'll see if I can view it live. Thanks.
