### ISSUE TITLE
How does generation work for autoregressive models?

### ISSUE THREAD

**Issue by YHYeooooong** [EugenHotaj/pytorch-generative#34]
Thank you for sharing good codes!
and Sorry for asking you about the original paper, but I can not find where to ask. 😭

I am trying to understand the Pixel CNN and I don't know how the mode generates images from zero tensor input.
Most of the codes feed the zero tensor into the models for generations.

I think,
If zero input comes into the model, and model may compute only the bias values in layers ( 0 tensor + bias ).
And results of the model are the same because the same bias values are computed every try for generating an image.
So the model generates the same image each tries to generate.

But the model looks like generates a different image on every try. 
How does the model generate an image from zero tensor input? Is there are any noise values or random sampling functions thing?

**Comment by EugenHotaj** [comment]
@YHYeooooong

For unconditional generation, the input tensor is ignored. It doesn't matter if you use a `0` tensor, a random tensor, or even an existing image. We just need some tensor to hold the results that are generated.

For unconditional image generation, we generate one pixel at a time in [raster scan order](https://en.wikipedia.org/wiki/Raster_scan). For the first pixel (top-left) we sample from the "prior"*, which in practice means we use just the biases to generate the NN output. This output is interpreted as a probability distribution and we sample from it to get our first pixel. Then we feed this pixel into the NN to generate out second pixel. Then we feed both pixels into the NN to generate our third pixel. And so on until we've generated all pixels.

For conditional generation, we use some existing pixels (e.g. part of an image) and pretend the network generated them by feeding them as inputs to generate the next pixel.

Hope that clears things up.

* This is not a true prior in the Bayesian sense because we're learning it from data.

**Comment by YHYeooooong** [comment]
Thanks !!!
